version: 2.1

orbs:
    node: circleci/node@5.0
jobs:
    build-and-test:
        docker:
            - image: cimg/node:18.18
        steps:
            - checkout
            - run:
                  name: Install package
                  command: npm install --legacy-peer-deps
            - run:
                  name: Run build
                  command: export CI=false && npm run build
    deploy:
        machine:
            image: "ubuntu-2004:current"
        steps:
            - checkout
            - run:
                  name: Fix ssh Could not resolve hostname
                  command: |
                      pwd
                      ls -lah
                      ssh-keyscan ${SSH_HOST} >> ~/.ssh/known_hosts # Add live server IP to known hosts.

            - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
                  fingerprints:
                      - "ac:86:a1:91:f7:5c:b2:65:1c:7f:81:0e:ae:60:81:30"

            - run:
                  name: Deploy to EC2
                  command: ssh ${SSH_USERNAME}@${SSH_HOST} 'bash -s -i' < .circleci/deploy.sh

workflows:
    HeartHead:
        jobs:
            - build-and-test
            - deploy:
                  requires:
                      - build-and-test
