const InformationWeCollect = () => {
    return (
        <>
            <p>
                The types of personal information we collect depend on how you
                interact with us, our Services, and the requirements of
                applicable law. We collect information that you provide to us,
                information we obtain automatically when you use our Services,
                and information from other sources such as third-party services
                and organizations, as described below:
            </p>
            <br />

            <p>
                **a. Information You Provide:** This category pertains to any
                data that you directly provide to us while using our Services.
                Examples of such information include:
            </p>
            <br />

            <p>
                - Personal details: Name, email address, phone number, and other
                contact information.
            </p>
            <p>
                - Account information: Usernames, passwords, and other security
                credentials.
            </p>
            <p>
                - Payment information: Payment card details, billing addresses,
                and transaction history.
            </p>
            <p>
                - User-generated content: Any content, comments, or
                contributions you submit to our Services.
            </p>
            <br />

            <p>
                **b. Automatically Collected Information:** We also gather
                certain information automatically when you interact with our
                Services. This may include:
            </p>
            <br />

            <p>
                - Device information: Details about the devices you use to
                access our Services, such as device type, operating system, and
                unique device identifiers.
            </p>
            <p>
                - Log data: Information generated by your interactions with our
                Services, including log files, error reports, and usage data.
            </p>
            <p>
                - Location information: Your approximate location based on IP
                address or other geolocation data.
            </p>
            <p>
                - Usage data: Details about how you use our Services, including
                browsing history, search queries, and feature interactions.
            </p>
            <br />

            <p>
                We employ various technologies, including cookies, web beacons,
                and similar tracking mechanisms, to collect this data. For more
                information on our use of cookies, please refer to our Cookies
                Policy.
            </p>
            <br />

            <p>
                **c. Information from Other Sources:** HEX TOYS LTD may receive
                information about you from third-party services and
                organizations to enhance our understanding of your preferences
                and provide you with a more personalized experience. This
                information may include:
            </p>
            <br />

            <p>
                - Additional user information: Demographic data, interests, and
                preferences.
            </p>
            <p>
                - Data from social media platforms: Information from your social
                media profiles or interactions.
            </p>
            <p>
                - Data from partners and affiliates: Information shared with us
                by our trusted partners and affiliates.
            </p>
            <br />

            <p>
                We may combine information collected from these various sources
                to better tailor our Services to your needs and preferences.
            </p>
            <br />

            <p>---</p>
            <br />

            <p>
                Please ensure that you review and adapt this section to align
                with the specific data collection practices and requirements of
                HEX TOYS LTD and consult with legal counsel to ensure compliance
                with relevant privacy laws and regulations.
            </p>
        </>
    );
};

export const PRIVACY_POLICY = [
    {
        title: "1. Information We Collect",
        text: <InformationWeCollect />,
    },
    {
        title: "2. How We Use Your Information",
        text: (
            <>
                <p>
                    2.1 We use your personal information to provide and improve
                    our services, respond to inquiries, and process
                    transactions.
                </p>
                <p>
                    2.2 Your information may be used for communication purposes,
                    such as sending important notices, updates, or promotional
                    material.
                </p>
                <p>
                    2.3 We may use aggregated and anonymized data for analytical
                    purposes.
                </p>
            </>
        ),
    },
    {
        title: "3. Data Security",
        text: (
            <>
                <p>
                    3.1 We employ industry-standard security measures to protect
                    your personal information from unauthorized access,
                    disclosure, alteration, and destruction.
                </p>
                <p>
                    3.2 Despite our efforts, please be aware that no data
                    transmission over the internet is completely secure, and we
                    cannot guarantee the absolute security of your data.
                </p>
            </>
        ),
    },
    {
        title: "4. Cookies and Similar Technologies",
        text: (
            <>
                <p>
                    4.1 We use cookies and similar technologies to enhance your
                    experience, analyze trends, and administer the website.
                </p>
                <p>
                    4.2 You can manage your cookie preferences through your
                    browser settings.
                </p>
            </>
        ),
    },
    {
        title: "5. Third-Party Links",
        text: "Our website may contain links to third-party websites. We are not responsible for the privacy practices or content of these third-party sites.",
    },
    {
        title: "6. Changes to this Privacy Policy",
        text: "We reserve the right to update this Privacy Policy at any time. Changes will be effective immediately upon posting the updated policy on the website.",
    },
    {
        title: "7. Your Choices",
        text: "You have the right to access, correct, or delete your personal information. You may also choose to opt-out of certain communications.",
    },
    {
        title: "8. Contact Information",
        text: (
            <>
                <p>
                    If you have any questions or concerns about this Privacy
                    Policy, please contact us at [Your Contact Email].By using
                    [Your Crypto Website],
                </p>{" "}
                <p>
                    you acknowledge that you have read and understood this
                    Privacy Policy.
                </p>{" "}
            </>
        ),
    },
    // {
    //     title: "",
    //     text: "",
    // },
    // {
    //     title: "",
    //     text: "",
    // },
];
